### PR TITLE
data initialize was added.

### PR DESCRIPTION
**Pull request by HernanGH**
I don't know if this simple implementation solved the issue. Let me know if you have some suggestions.

### CODE REVIEW

**Comment by ivanhuay** [comment]
sorry, it was a misunderstanding we need a default value for empty code but for each no create the first challenge. Also, the challenge only works for 24 hours so this won't work.

We need something like pre-save for the challenge model and validate the code property if it's empty fill it with the base code.

**Review by ivanhuay — CHANGES_REQUESTED** [review]
sorry, it was a misunderstanding we need a default value for empty code but for each no create the first challenge. Also, the challenge only works for 24 hours so this won't work.

We need something like pre-save for the challenge model and validate the code property if it's empty fill it with the base code.

**Comment by HernanGH** [comment]
What do you refer with `base code`?
I think that `console.log("Test")` it's correct.

**Review by ivanhuay — APPROVED** [review]
looks ok 👍

**Pull request merged**
